name: Kaikorero
options:
  bundleIdPrefix: com.kaikorero
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: HK6R36PLNR
    SWIFT_VERSION: "6.2"
    GENERATE_INFOPLIST_FILE: true

packages:
  SwiftFSRS:
    url: https://github.com/4rays/swift-fsrs
    from: "0.9.2"

targets:
  Kaikorero:
    type: application
    platform: iOS
    sources:
      - path: Kaikorero
        excludes:
          - Resources/Audio/.gitkeep
    resources:
      - path: Kaikorero/Resources/Assets.xcassets
      - path: Kaikorero/Resources/Data
      - path: Kaikorero/Resources/Audio
        excludes:
          - .gitkeep
    entitlements:
      path: Kaikorero/Kaikorero.entitlements
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.kaikorero.app
        PRODUCT_NAME: Kaikōrero
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: SwiftFSRS

  KaikoreroTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KaikoreroTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kaikorero.tests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: Kaikorero

schemes:
  Kaikorero:
    build:
      targets:
        Kaikorero: all
        KaikoreroTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KaikoreroTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
