name: Kaikorero
options:
  bundleIdPrefix: nz.ursa
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

fileGroups:
  - Kaikorero/Kaikorero.entitlements
  - Kaikorero/Resources/PrivacyInfo.xcprivacy

settings:
  base:
    DEVELOPMENT_TEAM: HK6R36PLNR
    SWIFT_VERSION: "6.2"
    GENERATE_INFOPLIST_FILE: true
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: YES

packages:
  SwiftFSRS:
    url: https://github.com/4rays/swift-fsrs
    from: "0.9.2"

targets:
  Kaikorero:
    type: application
    platform: iOS
    sources:
      - path: Kaikorero
        excludes:
          - Resources/Audio/.gitkeep
    resources:
      - path: Kaikorero/Resources/Assets.xcassets
      - path: Kaikorero/Resources/Data
      - path: Kaikorero/Resources/Audio
        excludes:
          - .gitkeep
      - path: Kaikorero/Resources/PrivacyInfo.xcprivacy
    info:
      path: Kaikorero/Info.plist
      properties:
        UIBackgroundModes:
          - remote-notification
    entitlements:
      path: Kaikorero/Kaikorero.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.cornelius-bell.kaikorero
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)$(CFBundleIdentifier)
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: nz.ursa.kaikorero
        PRODUCT_NAME: Kaikorero
        INFOPLIST_KEY_CFBundleDisplayName: Kaikōrero
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.education"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: SwiftFSRS

  KaikoreroTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KaikoreroTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nz.ursa.kaikorero.tests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: Kaikorero

schemes:
  Kaikorero:
    build:
      targets:
        Kaikorero: all
        KaikoreroTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KaikoreroTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
